description: left atrial segmentation pipeline
modality: MRI
preprocess:
  train:
    - name: "RandomRotation"
    - name: "RandomFlip"
    - name: "RandomCrop"
      variables:
        output_size: [112, 112, 80]

  test: